language: python
python:
  - '3.7'
os: linux
dist: xenial
arch: amd64

install:
  - pip install poetry
  - poetry install

before_script:
  - poetry run ./scripts/lint.py || (echo -n)

script: ./scripts/travisci-script-phase.bash
